# service configuration
nichetoolkit.rice.service.delete-mode=remove
nichetoolkit.rice.service.delete.logic-mode=config
nichetoolkit.rice.service.delete.config-mark=number
nichetoolkit.rice.service.delete.auto-mark=identity
nichetoolkit.rice.service.delete.accurate-judge=true
nichetoolkit.rice.service.dynamic-table=true

# mysql table configuration
nichetoolkit.mybatis.table.catalog=
nichetoolkit.mybatis.table.schema=
nichetoolkit.mybatis.table.use-logic=true
nichetoolkit.mybatis.table.use-operate=false
nichetoolkit.mybatis.table.update-logic=false
nichetoolkit.mybatis.table.exclude-unused=false
nichetoolkit.mybatis.table.sql-script-show=true
nichetoolkit.mybatis.table.mysql-ignore-insert=false
nichetoolkit.mybatis.table.datetime-now=now()
nichetoolkit.mybatis.table.database-type=mysql
nichetoolkit.mybatis.table.style-type=lower_underline
nichetoolkit.mybatis.table.excluded-type=values
nichetoolkit.mybatis.table.excludes=
nichetoolkit.mybatis.table.ignores=

# mysql datasource configuration
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/dynamic_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
spring.datasource.hikari.username=root
spring.datasource.hikari.password=2314
